version: '3.8'

services:
  react-app:
    image: node:18
    working_dir: /app
    volumes:
      - ./react-app:/app
    command: sh -c "npm install && npm run build"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./react-app/build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react-app